### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by jpsbur** [testsys/ball#1]
Rewrite import in python, reuse code

**Comment by jpsbur** [comment]
Started at https://github.com/testsys/ball/commit/6845742b2d25d7f5e480475047e0494680138d03

**Comment by jpsbur** [comment]
Working version exists since https://github.com/testsys/ball/commit/e38d65f7ca06b6eaa30c0bce656eb4ddea8cf6b7

Next steps: do not re-import existing balloons (cut by time or id)

**Comment by burunduk3** [comment]
Some improvements in 41cc0adc926ea3b50b5bab88ca038f7123b3e5fd.
May be in future it will be possible to get data from testing system not in snapshots, but via updates stream making better optimization possible. For now we have to parse every contest data file from scratch every time, for example, because some old submission could be rejudged and became OK.
